Idea dropdown replacement
Leantime/leantime pull request #2658
Opened 2024-09-12 16:23 UTC by muhtasimhafiz

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Link to ticket

Please add a link to the GitHub issue being addressed by this change.

### Type

[] Fix
[] Feature
[] Cleanup 

#### Screenshot of the result

If your change affects the user interface, you should include a screenshot of the result with the pull request.

2024-09-12 17:22 UTC, marcelfolaron requested changes

2024-09-12 17:22 UTC, marcelfolaron commented on app/Domain/Goalcanvas/Templates/showCanvas.blade.php
> +                                <x-global::actions.dropdown :labelText="html_entity_decode($labelText)" class="btn dropdown-toggle" align="start"
Can you update this to use <x-slot:label-Text> and remove the html_entity_decode?

2024-09-12 17:22 UTC, marcelfolaron commented on app/Domain/Ideas/Templates/advancedBoards.blade.php
> +                                                            :labelText="html_entity_decode($labelText)"
Move into slot for label-text and remove html_entity_decode

2024-09-12 17:22 UTC, marcelfolaron commented on app/Domain/Ideas/Templates/advancedBoards.blade.php
> +                                    aripa-hidden="true">&times;</button>
typo?

2024-09-12 17:22 UTC, marcelfolaron commented on app/Views/Templates/components/actions/dropdown/item.blade.php
> +    'variant' => 'link', // Variant of the dropdown item: 'link', 'border', 'nav-header', or 'nav-header-border'
can we just keep the name the variants "header" and "border". the nav-XXX seems rather long and the border doesn't always have to be near a header :D ?

2024-09-12 17:22 UTC, marcelfolaron commented on app/Views/Templates/components/actions/dropdown/item.blade.php
> +    'variant' => 'link', // Variant of the dropdown item: 'link', 'border', 'nav-header', or 'nav-header-border'
PS: Should have looked at the file first. 

header
border
header-border


Should be fine

2024-09-12 18:18 UTC, muhtasimhafiz commented on app/Domain/Ideas/Templates/advancedBoards.blade.php
> +                                    aripa-hidden="true">&times;</button>
fixed

2024-09-13 01:17 UTC, marcelfolaron approved these changes

2024-09-13 01:18 UTC, merged